#
# Voice Signal Preprocess
# Copyright (C) 2001-2024 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_LVP_KWS_VIVA_GENERAL_ASR_FAN_V103_V055_UNIVERSAL_450K_MODEL_V0DOT5DOT5_2024_0806), y)

MODEL_DIR_PRE  = lvp/vui/kws/models/viva_general_asr_fan_v103_v055/v1.0.3_v0.5.5

INCLUDE_DIR    += $(MODEL_DIR_PRE)/
INCLUDE_DIR    += $(MODEL_DIR_PRE)/../
kws_objs       += $(MODEL_DIR_PRE)/ctc_model.o

endif