INCLUDE_DIR += lvp/common/custom_space/

ifeq ($(CONFIG_ENABLE_CLOSE_CMD_RECOGNIZE), y)
custom_space_objs += lvp/common/custom_space/close_recognize/lvp_close_recognize.o
endif
ifeq ($(CONFIG_ENABLE_STORAGE_CUSTOM_DATA), y)
custom_space_objs += lvp/common/custom_space/write_custom_data/lvp_write_custom_data.o
endif
