#
# Voice Signal Preprocess
# Copyright (C) 2001-2023 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list of app
#
#=================================================================================#

INCLUDE_DIR += lvp/app_core

-include app/*/app.mk

