# 芯片类型，设置想要运行的芯片类型，如：GX8002D 或 GX8003A
chip_name: "GX8003A" #LVP 工程支持的芯片
# chip_name: "GX8002D" #LVP 工程支持的芯片
# chip_name: "GX8302B" #APUS 工程支持的芯片
# chip_name: "GX8008C" #VSP 工程支持的芯片

# 想要新建app时可以打开注释，并设置成自己想要的名字
# app_name: "user_app"

# 模型部署名称，根据模型应用需求配置。如果是已经部署过的模型的迭代，需保持与已有模型的命名一致。如有需要，使用下划线做分割。
model_name: "general_dryer_demo"

model_version: v5.0.4
# model_version: v0.1.2 #APUS 下的声学模型版本
new_model: Y
update_model: Y
update_language_model: Y
lvp_tws_path: "../lvp_aiot/lvp/vui/kws/"                                      # LVP SDK 模型存放路径
# lvp_tws_path: "robotos/apus/apps/ai_voice/src/kws/model_fst/"                # APUS SDK 模型存放路径
# lvp_tws_path: "../../vsp/dsp/vpa/olab_op/src/rock/kws/gxdecoder/model_fst/"  # VSP SDK 模型存放路径

# vpa_simulate_path: "../../lvp/vpa_simulate/vpa/lvp/src/vui/kws/" # 注释掉即可，不需关心
major_kws_misactive_number: 3
command_word_misactive_number: 8
immediate_command_word_misactive_number: 3
threshold_updated_to_kws_list: Y
print_uart: 1       # 打开注释则开启串口打印，设置值为使用的 串口号

# 设置脚本运行可使用的cpu个数，可根据自己的电脑配置修改【要小于电脑实际cpu数 - 1】
cpu_count: 1

# 语言模型标志位, 在含有三个字的指令词，并且这个指令词与其它词具有包含关系时可设置为1
lm_3char_inclusion_flag: 0

# 当串词严重的时候，可通过降低或升高某个词的概率来进行微调，设置的系数范围 0 < 系数 < 2，(1, 2) 降低概率，(0, 1) 升高概率
# words_probability_fine_tuned:
#   打开冷风: 1.5
#   关闭冷风: 0.5

# tts语言风格,只可选择一个。不需要tts播报，可将此字段删除，或在后面填 " null"，注意 yml文件语法冒号与设置的值中间有个空格
tts_style:
#  - mowenxuan_meet         # 男声--魔文轩-磁性温和,爽朗动听
#  - billy_meet             # 男声--魔小杰-纯净动听,朗朗悦耳
#  - baibianjianzhang_meet  # 男声--百变舰长-阳光帅气,爽朗动听
#  - moshuqi_meet           # 女声--魔殊琪--温柔甜美,自然动听
#  - monuandong_meet        # 女声--魔暖冬--元气少女,自然流畅
#  - molajiao_meet          # 女声--魔辣椒--温柔甜美,自然动听
#  - mofangguan_meet        # 女声--魔芳官--成熟温柔,自然流畅
#  - mercury_xiaoxiao       # 女声--小柔--纯净甜美,自然动听
#  - mercury_hsiaochen      # 女声--台湾晓臻--亲切温和,淳朴自然
#  - jupiter_BV001          # 女声--抖音小姐姐--温柔甜美,自然动听
#  - F110_meet              # 女声--小依--温柔柔软,清新甜美
 - moyunxuan_meet         # 女声--魔芸萱-温柔甜美,自然动听
#  - moxiaoqif_meet         # 女声--魔小琪-温柔知性,温婉大方
#  - caicai_meet            # 女声--采采-幽默诙谐,亲切甜美

# tts播放音量，默认 50， 越小声音越轻
tts_volume: 50
# tts播放速度，默认 50， 越小越慢
tts_speed: 50
# 超时时间
time_out_duration: 10

# 自定义播报内容，若想将文本替换成指定的音频可在括号内写指定路径
# custom_broadcast:
#   - 滴(tts_play/resource_wav/蜂鸣器声.wav)
#   - 自定义播报文本

# 开机tts播报，没有开机播报可将此字段删除，或在后面填 " null"，注意 yml文件语法冒号与设置的值中间有个空格
power_on_tts:
  - 欢迎使用智能晾衣架
# 超时tts播报，没有超时播报可将此字段删除，或在后面填 " null"，注意 yml文件语法冒号与设置的值中间有个空格
time_out_tts:
  - 再见

# 想要在串口接收到特定指令时进行播报响应可以打开下面注释
# # 设置使用的串口
# uart_port: 1
# # 设置使用的波特率
# uart_baudrate: 9600
# # 设置串口接收到对应指令的回复播报
# # 格式: uart_data@播报文本，当串口接收到和uart_data一致的数据时，开始播报后面的文本
# # 需要 uart_data 的长度一致，不一致时将按照最长的长度在后面补零
# uart_tts_reply_list:
#  - A0 A1 A2 00@欢迎使用智能晾衣架
#  - A0 A1 A2 01@开始遥控机对码
#  - A0 A1 A2 02@遥控机对码成功
#  - A0 A1 A2 03@遥控机对码失败

# 主唤醒词列表，没有可将此字段删除，或在后面填 " null"，注意 yml文件语法冒号与设置的值中间有个空格
major_list:
  - 小号小号|小一小一

# 免唤醒词列表，没有可将此字段删除，或在后面填 " null"，注意 yml文件语法冒号与设置的值中间有个空格
immediate_command_word_list:
  - 音量增大
  - 音量减小

# 唤醒词列表，需要需要包括 主唤醒词、免唤醒词 与 指令词 三部分
# 设置格式: <唤醒词[|唤醒词]...>[<#>id][<@>播报文本], 顺序为 唤醒词、id、播报文本
# 注意设置多个唤醒词时符号"|"不可省略，主唤醒词设置多条播报时，符号"@"不可省略
# 主唤醒词最多支持3条不同的TTS播报，指令词只支持一条TTS播报
words_list:
  - 小号小号|小一小一#100@你说@我在呢
  - 打开照明|照明打开@照明已打开
  - 关闭照明|照明关闭@照明已关闭
  - 晾杆上升|衣架上升@晾杆上升中
  - 晾杆下降|衣架下降@晾杆下降中
  - 停止升降|暂停升降
  - 衣架停止
  - 打开消毒|消毒打开
  - 关闭消毒|消毒关闭
  - 打开吹风
  - 打开冷风
  - 关闭吹风
  - 关闭冷风
  - 打开烘干|烘干打开
  - 关闭烘干|烘干关闭
  - 衣架全关
  - 功能全关
  - 音量增大
  - 音量减小

# 想要设置自学习功能可以打开下面注释
# self_learning:
#   led_pid: 1                                      # 使用点灯进行提示，设置值为使用的 引脚号
#   mute_time: 4                                    # 设置在连续静音几个context时认为是静音
#   repetition_count: 3                             # 一个词学习几遍，一般为2-3次
#   basic_learning_command: # 默认从32开始
#     - 学习指令词#31@开始学习指令词，请在安静环境下说话。  # 连续学习指令词的开始指令，不需要时可以删除，其id固定为31
#     - 删除所有指令词#32@已清除所有指令词学习数据
#     - 重置学习#33@已重置
#     - 退出学习#34@学习中止，已退出
#   learn_command_info:     # 学习的指令词信息, 需要注意书写顺序，先写免唤醒词，再写唤醒词，最后写指令词。
#     - kws_value: 100
#       major: 1
#       learning_phrase: 学习唤醒词@开始学习唤醒词，请在安静环境下说话。学习后可用该指令唤醒，请说
#       delete_phrase: 删除唤醒词@已清除唤醒词学习数据
#     - kws_value: 101
#       major: 0
#       learning_phrase: 学习开灯指令@开始学习开灯指令，学习后可用该指令开灯，请说
#       delete_phrase: 删除开灯指令@已清除开灯指令学习数据
#     - kws_value: 102
#       major: 0
#       learning_phrase: 学习关灯指令@开始学习关灯指令，学习后可用该指令关灯，请说
#       delete_phrase: 删除关灯指令@已清除关灯指令学习数据
#   broadcast_messages:     # 注意播报id自动从35开始
#     - 学习成功，请再说一次#35                        # 学习成功播报
#     - 学习失败，请再说一次#36                        # 学习失败播报
#     - 学习完成#37                                  # 学习完成播报
#     - 本次学习与已学习的记录一致，请更换词条再说一次#38  # 在学习过程中，当前学习到的指令在先前已经学习过时的播报
#     - 学习异常，将重置学习#39                        # 学习遇到异常情况时播报
#     - 请清除学习唤醒词后，再开始学习#40                # 在有唤醒词学习记录时，还要进行学习时播报
#     - 请清除学习指令词后，再开始学习#41                # 在有指令词学习记录时，还要进行学习时播报
#     - 请清除学习免唤醒词后，再开始学习#42              # 在有免唤醒词学习记录时，还要进行学习时播报
#     - 清除唤醒词失败，将重置学习#43                   # 在清除唤醒词失败时播报
#     - 清除指令词失败，将重置学习#44                   # 在清除指令词失败时播报
#     - 清除免唤醒词失败，将重置学习#45                 # 在清除免唤醒词失败时播报
#     - 还没有学习数据#46                             # 清除还未学习过的指令时播报
#     - 学习数据过多，未成功写入flash，学习失败。#47      # 写入flash失败时播报

