#
# Voice Signal Preprocess
# Copyright (C) 2001-2024 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_LVP_KWS_VIVA_GENERAL_DRYER_DEMO_DRYING_RACK_EXCLUSIVE_MODEL_V5DOT0DOT4_2024_0725), y)

MODEL_DIR_PRE  = lvp/vui/kws/models/viva_general_dryer_demo/drying_rack_exclusive_model_v5.0.4

INCLUDE_DIR    += $(MODEL_DIR_PRE)/
INCLUDE_DIR    += $(MODEL_DIR_PRE)/../
kws_objs       += $(MODEL_DIR_PRE)/ctc_model.o

endif