#
# Voice Signal Preprocess
# Copyright (C) 2001-2024 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_LVP_KWS_VIVA_BLE_SAMPLE_LIGHT_EXCLUSIVE_MODEL_V6DOT0DOT2_2024_0905), y)

MODEL_DIR_PRE  = lvp/vui/kws/models/viva_ble_sample/light_exclusive_model_v6.0.2

INCLUDE_DIR    += $(MODEL_DIR_PRE)/
INCLUDE_DIR    += $(MODEL_DIR_PRE)/../
kws_objs       += $(MODEL_DIR_PRE)/ctc_model.o

endif